new commit

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -65,46 +65,69 @@ jobs:
         with:
           args: --sarif-file-output=snyk.sarif
   build_and_test:
-
     runs-on: ubuntu-latest
-
+    needs: compile
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 14
-        uses: actions/setup-java@v1
-        with:
-          java-version: 14
-
-      - name: Build project with Maven
-        run: mvn -B package --file pom.xml
-  build:
-    name: Build and Analyze
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 11
-      - name: Cache SonarQube packages
-        uses: actions/cache@v1
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache Maven packages
-        uses: actions/cache@v1
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Build and analyze
+    - uses: actions/checkout@v2
+    - uses: actions/cache@v2
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-
+    - name: Set up JDK 14
+      uses: actions/setup-java@v1
+      with:
+        java-version: 14
+    - name: Check working directory
+      run: echo "${GITHUB_WORKSPACE}"
+    - name: Build project with Maven
+      run: | 
+           mvn -B package --file pom.xml
+           mkdir staging && cp target/*.jar staging/ 
+    - name: Test
+      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: target/surefire-reports/TEST-*.xml    # Path to test results
+        reporter: java-junit       # Format of test results
+        fail-on-error: 'false'
+    - name: Build and analyze
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gargimehendale_testci
+#  build:
+#    name: Build and Analyze
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 11
+#      - name: Cache SonarQube packages
+#        uses: actions/cache@v1
+#        with:
+#          path: ~/.sonar/cache
+#          key: ${{ runner.os }}-sonar
+#          restore-keys: ${{ runner.os }}-sonar
+#      - name: Cache Maven packages
+#        uses: actions/cache@v1
+#        with:
+#          path: ~/.m2
+#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: ${{ runner.os }}-m2
+#      - name: Build and analyze
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=gargimehendale_testci
   Upload_Artifact:
     runs-on: ubuntu-latest
     needs: build_and_test
@@ -113,20 +136,50 @@ jobs:
     - uses: actions/setup-java@v1
       with:
         java-version: 14
-    - run: mvn -B package --file pom.xml -DskipTests
-    - run: mkdir staging && cp target/*.jar staging
-    - name: Cache Maven packages
-      uses: actions/cache@v1
+        distribution: 'adopt'
+    - run: mvn --batch-mode --update-snapshots verify
+    - run: mkdir staging && cp target/jb-hello-world-maven-0.2.0.jar staging
+    - name: Check file existence
+      id: check_files
+      uses: andstor/file-existence-action@v1
       with:
-        path: ~/.m2
-        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-        restore-keys: ${{ runner.os }}-m2
-    - uses: actions/upload-artifact@v2
+        files: staging/jb-hello-world-maven-0.2.0.jar
+
+    - name: File exists
+      if: steps.check_files.outputs.files_exists == 'true'
+      run: echo "It exists !"
+    - uses: actions/upload-artifact@v3
       with:
-        name: github-actions-artifact
+        name: Package
         path: staging
    # - name: Upload Maven build artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: artifact.jar
    #     path: github-actions-java-maven/target/github-actions-java-maven.jar
+  deploy:
+    runs-on: ubuntu-latest
+    needs: Upload_Artifact
+
+    steps:
+    - uses: actions/checkout@v2
+    - uses: actions/download-artifact@v1
+      with:
+        name: package
+        path: target/
+    - name: Generate build number
+      id: buildnumber
+      uses: einaregilsson/build-number@v3 
+      with:
+        token: ${{secrets.github_token}} 	
+    - name: Login to DockerHub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKERHUB_USER }}
+        password: ${{ secrets.DOCKERHUB_TOKEN_INCEPTION }}
+    - name: Build and Push docker image
+      uses: docker/build-push-action@v3
+      with: 
+        context: .
+        push: true
+        tags: infracloudinception/cicd_inception:${{ steps.buildnumber.outputs.build_number }}
